import { Router } from 'express';
const router: Router = Router();

import uploadRoutes from './uploadRoutes';
import authRoutes from './authRoutes';
import healthRoutes from './healthRoutes';
import tripRoutes from './tripRoutes';
import dashboardRoutes from './dashboardRoutes';
import seatLockRoutes from './seatLockRoutes';
import planRoutes from './planRoutes';
import paymentMethodRoutes from './paymentMethodRoutes';
import subscriptionRoutes from './subscriptionRoutes';
import adminSubscriptionRoutes from './adminSubscriptionRoutes';
import driverRoutes from './driverRoutes';
import driverVerificationRoutes from './driverVerificationRoutes';
import ratingRoutes from './ratingRoutes';
import complaintRoutes from './complaintRoutes';
import notificationRoutes from './notificationRoutes';
import notificationSettingRoutes from './notificationSettingRoutes';
import vehicleRoutes from './vehicleRoutes';
import adminVerificationRoutes from './adminVerificationRoutes';
import adminModerationRoutes from './adminModerationRoutes';
import adminDashboardRoutes from './adminDashboardRoutes';
import chatRoutes from './chatRoutes';
import sosRoutes from './sosRoutes';
import realtimeHealthRoutes from './realtimeHealthRoutes';
import bookingRoutes from './bookingRoutes';
import rideRequestRoutes from './rideRequestRoutes';
import offersRoutes from './offersRoutes';
import supportTicketRoutes from './supportTicketRoutes';
import favoriteRoutes from './favoriteRoutes';
import profileRoutes from './profileRoutes';

router.use('/healthz', healthRoutes);
router.use('/health', realtimeHealthRoutes);
router.use('/chat', chatRoutes);
router.use('/auth', authRoutes);
router.use('/upload', uploadRoutes);
router.use('/trips', tripRoutes);
router.use('/driver/dashboard', dashboardRoutes);
router.use('/driver', driverRoutes);
router.use('/driver', driverVerificationRoutes);
router.use('/trips', seatLockRoutes);
router.use('/plans', planRoutes);
router.use('/payment-methods', paymentMethodRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/admin', adminSubscriptionRoutes);
router.use('/admin/verification', adminVerificationRoutes);
router.use('/admin', adminModerationRoutes);
router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/admin', sosRoutes);
router.use('/bookings', bookingRoutes);
router.use('/ride-requests', rideRequestRoutes);
router.use('/offers', offersRoutes);
router.use('/support-tickets', supportTicketRoutes);
router.use('/favorites', favoriteRoutes);
router.use('/profile/passenger', profileRoutes);
router.use('/ratings', ratingRoutes);
router.use('/complaints', complaintRoutes);
router.use('/notifications', notificationRoutes);
router.use('/settings/notifications', notificationSettingRoutes);
router.use('/vehicles', vehicleRoutes);

export default router;
module.exports = router;
