const router = require('express').Router();

const uploadRoutes = require('./uploadRoutes');
const authRoutes = require('./authRoutes');
const healthRoutes = require('./healthRoutes');
const tripRoutes = require('./tripRoutes');
const dashboardRoutes = require('./dashboardRoutes');
const seatLockRoutes = require('./seatLockRoutes');
const planRoutes = require('./planRoutes');
const paymentMethodRoutes = require('./paymentMethodRoutes');
const subscriptionRoutes = require('./subscriptionRoutes');
const adminSubscriptionRoutes = require('./adminSubscriptionRoutes');
const driverRoutes = require('./driverRoutes');
const driverVerificationRoutes = require('./driverVerificationRoutes');
const ratingRoutes = require('./ratingRoutes');
const complaintRoutes = require('./complaintRoutes');
const notificationRoutes = require('./notificationRoutes');
const notificationSettingRoutes = require('./notificationSettingRoutes');
const vehicleRoutes = require('./vehicleRoutes');
const adminVerificationRoutes = require('./adminVerificationRoutes');
const adminModerationRoutes = require('./adminModerationRoutes');

router.use('/healthz', healthRoutes);
router.use('/auth', authRoutes);
router.use('/upload', uploadRoutes);
router.use('/trips', tripRoutes);
router.use('/driver/dashboard', dashboardRoutes);
router.use('/driver', driverRoutes);
router.use('/driver', driverVerificationRoutes);
router.use('/trips', seatLockRoutes);
router.use('/plans', planRoutes);
router.use('/payment-methods', paymentMethodRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/admin', adminSubscriptionRoutes);
router.use('/admin/verification', adminVerificationRoutes);
router.use('/admin', adminModerationRoutes);
router.use('/ratings', ratingRoutes);
router.use('/complaints', complaintRoutes);
router.use('/notifications', notificationRoutes);
router.use('/settings/notifications', notificationSettingRoutes);
router.use('/vehicles', vehicleRoutes);

module.exports = router;
